### PR TITLE
Hotfix: Slack messages for empty durations/descriptions and no-result runs

### LINKED ISSUE #52: Slack not working will with runs without results
screen shot 2015-12-02 at 1 53 21 pm

### PR DESCRIPTION
**Pull request by epaulet**
fixes #52

### CODE REVIEW

File: lib/integrations/message_formatter.rb [hunk 1]
```diff
@@ -12,7 +12,8 @@ def run_href
     end
 
     def run_description
-      run[:description] ? ": #{run[:description]}" : ""
+      description = run[:description]
+      (description && description.length > 0) ? ": #{description}" : ""
```
Comment (shosti) [inline lib/integrations/message_formatter.rb]: Can do `run[:description].present?` instead I think.

**Comment by shosti** [comment]
LGTM other than nitpicks.
